# DATABASE CONFIG
DB_LOGIN = "alex"
DB_PASSWORD = "otvertka"
DB_ADDRESS = "localhost"
DB_NAME = "test_db"

# PREMIUM CONFIGS
TRIAL_PERIOD_SECONDS = 3600 * 24
REFERER_PERIOD_SECONDS = 3600 * 24


# LANGUAGE CONFIGS
DEFAULT_LANGUAGE = 'ru'

